// Contraction maps organised by BCP-47 locale code.
// Extend this object to support more languages.
export const CONTRACTION_MAPS: Record<string, Record<string, string>> = {
  en: {
    "can't": "cannot",
    "won't": "will not",
    "i'm": "i am",
    "it's": "it is",
    "he's": "he is",
    "she's": "she is",
    "they're": "they are",
    "we're": "we are",
    "isn't": "is not",
    "aren't": "are not",
    "wasn't": "was not",
    "weren't": "were not",
    "don't": "do not",
    "doesn't": "does not",
    "didn't": "did not",
    "hasn't": "has not",
    "haven't": "have not",
    "hadn't": "had not",
    "shouldn't": "should not",
    "wouldn't": "would not",
    "couldn't": "could not",
    "mustn't": "must not",
    "let's": "let us",
    "there's": "there is",
    "that's": "that is",
    "what's": "what is",
    "who's": "who is",
    "where's": "where is",
    "when's": "when is",
    "why's": "why is",
    "how's": "how is",
    "i've": "i have",
    "we've": "we have",
    "they've": "they have",
    "should've": "should have",
    "would've": "would have",
    "could've": "could have",
    "i'll": "i will",
    "he'll": "he will",
    "she'll": "she will",
    "we'll": "we will",
    "they'll": "they will",
    "it'll": "it will",
    "who'll": "who will",
    "can't've": "cannot have",
    "n't": " not", // catch-all generic pattern
    "y'all": "you all",
    "y\u2019all": "you all"
  },
  fr: {
    "c'est": "ce est",
    "j'ai": "je ai",
    "j'aime": "je aime",
    "n'est": "ne est",
    "qu'il": "que il",
  },
  de: {
    "am": "an dem",
    "im": "in dem",
    "zum": "zu dem",
    "zur": "zu der",
    "beim": "bei dem",
    "vom": "von dem",
    "ins": "in das",
  },
  sq: {
    "s'ka": "s ka",
    "s'jam": "s jam",
  },
  he: {
    "מ'": "מ",
    "ל'": "ל",
    "ש'": "ש",
  },
  es: {
    "al": "a el",
    "del": "de el",
  },
  zh: {
    "没": "没有",
    "啥": "什么",
    "咱": "我们",
    "咋": "怎么",
  },
  yue: {
    "冇": "沒有",
    "喺": "在",
  },
}; 